/**
 * 바이브 카페 기본 데이터 및 Supabase SQL 쿼리문
 */
import { BeverageItem, SizeOption, ExtraOption } from '../types';

// 1. 음료 메뉴 목록 (기본 단가 포함)
export const BEVERAGE_MENU: BeverageItem[] = [
  { id: 'americano', name: '아메리카노', price: 3500, emoji: '☕', description: '깊고 진한 풍미의 고소한 에스프레소 아메리카노' },
  { id: 'caffe_latte', name: '카페라떼', price: 4000, emoji: '🥛', description: '부드러운 스팀밀크와 에스프레소의 조화' },
  { id: 'caffe_mocha', name: '카페모카', price: 4500, emoji: '🍫', description: '달콤한 초콜릿과 진한 커피의 만남' },
  { id: 'vanilla_latte', name: '바닐라라떼', price: 4500, emoji: '🍦', description: '천연 바닐라 빈 시럽의 달콤하고 향긋한 라떼' },
  { id: 'green_tea_latte', name: '녹차라떼', price: 4500, emoji: '🍵', description: '제주산 유기농 말차 가루로 만든 깊은 녹차 라떼' },
];

// 2. 음료 사이즈 목록 (M 기본 선택, +500원)
export const SIZE_OPTIONS: SizeOption[] = [
  { id: 'S', name: 'S', extraPrice: 0 },
  { id: 'M', name: 'M', extraPrice: 500 },
  { id: 'L', name: 'L', extraPrice: 1000 },
];

// 3. 추가 옵션 목록
export const EXTRA_OPTIONS: ExtraOption[] = [
  { id: 'shot', name: '샷 추가', extraPrice: 500 },
  { id: 'cream', name: '크림 추가', extraPrice: 500 },
  { id: 'syrup', name: '시럽 추가', extraPrice: 300 },
  { id: 'decaf', name: '디카페인', extraPrice: 0 },
];

// 4. Supabase SQL Editor에서 실행할 테이블 생성 및 테스트 데이터 INSERT 쿼리문
export const SUPABASE_SQL_SCRIPT = `-- ====================================================================
-- [바이브 카페] Supabase SQL Editor 복사용 쿼리문
-- 1. cafe_menu 테이블 생성 쿼리 (주문서 항목 기반)
-- 2. 테스트용 1건 가짜 데이터 INSERT 쿼리
-- ====================================================================

-- 1. cafe_menu 테이블 생성
CREATE TABLE IF NOT EXISTS cafe_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 고유 주문 ID
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL, -- 주문 접수 일시
  customer_name VARCHAR(100) NOT NULL,                    -- 1. 고객 이름 (필수)
  phone VARCHAR(30),                                      -- 2. 전화번호
  beverage VARCHAR(100) NOT NULL,                         -- 3. 음료 선택 (아메리카노, 카페라떼 등)
  beverage_price INTEGER NOT NULL,                        -- 음료 기본 가격 (원)
  cup_size VARCHAR(10) NOT NULL DEFAULT 'M',              -- 4. 사이즈 (S, M, L)
  size_price INTEGER NOT NULL DEFAULT 500,                -- 사이즈 추가 금액 (0원, 500원, 1000원)
  options TEXT[] DEFAULT '{}',                            -- 5. 추가 옵션 목록 (배열 형태)
  options_price INTEGER NOT NULL DEFAULT 0,               -- 추가 옵션 총 금액 (원)
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 10), -- 6. 수량 (1~10)
  request_notes TEXT,                                     -- 7. 요청사항
  total_price INTEGER NOT NULL,                           -- 총 결제/예상 금액 (원)
  order_status VARCHAR(20) DEFAULT '접수완료'             -- 주문 상태 ('접수완료', '제조중', '수령완료')
);

-- 테이블 설명 코멘트 추가
COMMENT ON TABLE cafe_menu IS '바이브 카페 고객 주문 및 메뉴 데이터 테이블';
COMMENT ON COLUMN cafe_menu.customer_name IS '주문자 성함';
COMMENT ON COLUMN cafe_menu.phone IS '주문자 연락처';
COMMENT ON COLUMN cafe_menu.beverage IS '주문 음료명';
COMMENT ON COLUMN cafe_menu.cup_size IS '컵 사이즈 (S, M, L)';
COMMENT ON COLUMN cafe_menu.options IS '선택한 추가 옵션 목록 (배열)';
COMMENT ON COLUMN cafe_menu.quantity IS '주문 수량';
COMMENT ON COLUMN cafe_menu.total_price IS '최종 계산된 총 주문 금액';

-- 보안 및 접근 정책 (Row Level Security) 설정
ALTER TABLE cafe_menu ENABLE ROW LEVEL SECURITY;

-- 누구나 주문을 생성(INSERT)할 수 있도록 허용하는 정책
CREATE POLICY "누구나 주문 등록 가능" ON cafe_menu
  FOR INSERT WITH CHECK (true);

-- 주문 내역을 조회(SELECT)할 수 있도록 허용하는 정책
CREATE POLICY "누구나 주문 내역 조회 가능" ON cafe_menu
  FOR SELECT USING (true);


-- 2. 테스트용 1건 가짜 데이터 (Mock Data) INSERT 쿼리문
INSERT INTO cafe_menu (
  customer_name,
  phone,
  beverage,
  beverage_price,
  cup_size,
  size_price,
  options,
  options_price,
  quantity,
  request_notes,
  total_price,
  order_status
) VALUES (
  '홍길동',
  '010-1234-5678',
  '카페라떼',
  4000,
  'M',
  500,
  ARRAY['샷 추가'],
  500,
  1,
  '얼음 적게 부탁드립니다 ☕',
  5000,
  '접수완료'
);

-- 데이터 확인용 SELECT 쿼리
SELECT * FROM cafe_menu ORDER BY created_at DESC LIMIT 5;
`;
